language: python
python:
  - "2.7.15"
  - "3.6.6"
  - "3.7-dev"

dist: trusty

addons:
  apt:
    packages:
      - opencl-headers
      - ocl-icd-opencl-dev
      - fglrx

git:
  depth: false

install:
    # There is sometimes issues with the install order so do this bad boi first
  - pip install -r requirements.txt
  - pip install -e .

script:
  - python setup.py test