language: python
python:
  - "2.7.15"
  - "3.6.6"
  - "3.7-dev"

addons:
  apt:
    packages:
      - opencl-headers

git:
  depth: false

install:
  - pip install .

script:
  - "python setup.py test"