language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages: 
           - build-essential
           - ninja
           - openmpi-bin 
           - openmpi-doc 
           - libopenmpi-dev

script:
  - mkdir -p build
  - cd build
  - cmake ..
  - make